name: Test

on: [push, pull_request]

#env:
#  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
#        include:
          # Include new variables for Codecov
#          - { codecov-flag: GHA_Ubuntu, os: ubuntu-latest }
#          - { codecov-flag: GHA_macOS, os: macos-latest }

# - openjdk11
#- (cd sonar && mvn validate package)
#- ./gradlew check

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ant
        id: setup-ant
        run: |
          wget https://www.apache.org/dist/ant/binaries/apache-ant-1.10.9-bin.tar.gz
          tar -xzvf apache-ant-1.10.9-bin.tar.gz
          export PATH=`pwd`/apache-ant-1.10.9/bin:$PATH
          echo $(ant -version)

      - name: Fetch site via SVN
        id: setup-doc-site
        run: |
          svn co https://svn.apache.org/repos/asf/poi/site/src/documentation src/documentation

      - name: Tox tests
        shell: bash
        run: |
          ant clean jenkins
